apiVersion: v1
kind: Service
metadata:
  name: fastapi-test-service
spec:
  selector:
    app: fast-api-ml
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-ml
spec:
  selector:
    matchLabels:
      app: fast-api-ml
  replicas: 5
  template:
    metadata:
      labels:
        app: fast-api-ml
    spec:
      containers:
        - name: fast-api-ml
          image: fast-api-ml
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000